import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const URL='https://bcyvxxegkguygdbvxoth.supabase.co';
const KEY='sb_publishable_wILGSQL-gq4YMoZSeJ8rAQ_oviCl8BB';
const db=createClient(URL,KEY);
let session=null,me=null,partner=null,profile=null,received=[],authored=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));

function make(tag,cls,html=''){const el=document.createElement(tag);if(cls)el.className=cls;if(html)el.innerHTML=html;return el}
function screen(id,label){const el=make('section','cajita-screen');el.id=`screen-${id}`;el.dataset.screen=id;el.innerHTML=`<div class="screen-header"><span>NUESTRA CAJITA</span><h1>${label}</h1></div>`;return el}
function navigate(id){document.querySelectorAll('.cajita-screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));location.hash=id==='inicio'?'':id;window.scrollTo({top:0,behavior:'smooth'});$('.mobile-more-sheet')?.classList.add('hidden')}
function navButton(id,icon,label){const b=make('button','',`<span>${icon}</span>${label}`);b.dataset.nav=id;b.onclick=()=>id==='album'?location.href='/galeria.html':navigate(id);return b}

function buildShell(){if($('#cajitaLayout'))return;document.body.classList.add('cajita-ready');const app=$('#privateApp');const oldNav=app.querySelector('.top-nav');
const layout=make('div','cajita-layout');layout.id='cajitaLayout';const side=make('aside','cajita-sidebar');side.innerHTML=`<div class="cajita-brand">Bel & Jaime ❤️<small>nuestra cajita de recuerdos</small></div><div class="cajita-nav"></div>`;const content=make('div','cajita-content');const routes=[['inicio','🏠','Nuestra cajita'],['emergencias','🫂','Te necesito'],['capsulas','💌','Para el futuro'],['album','📷','Nuestro álbum'],['mapa','🗺️','Lugares por vivir'],['historia','📖','Nuestra historia'],['ajustes','⚙️','Por dentro']];routes.forEach(([id,ic,l])=>side.querySelector('.cajita-nav').append(navButton(id,ic,l)));layout.append(side,content);app.insertBefore(layout,oldNav?.nextSibling||app.firstChild);
const home=screen('inicio','Nuestra cajita');home.innerHTML+=`<div class="home-welcome card"><span class="eyebrow">UN RINCÓN SOLO NUESTRO</span><h2 id="personalGreeting">Hola ❤️</h2><p id="personalWelcome">Aquí guardamos todo lo que todavía nos queda por vivir.</p></div><div class="home-grid"><button class="home-link" data-home="emergencias"><span>🫂</span><strong>Te necesito</strong><small>Mensajes preparados por el otro</small></button><button class="home-link" data-home="capsulas"><span>💌</span><strong>Para el futuro</strong><small>Cápsulas y sorpresas pendientes</small></button><button class="home-link" data-home="album"><span>📷</span><strong>Nuestro álbum</strong><small>Los recuerdos que ya son nuestros</small></button><button class="home-link" data-home="mapa"><span>🗺️</span><strong>Lugares por vivir</strong><small>Viajes, restaurantes y escapadas</small></button></div>`;
const hero=app.querySelector('.hero');if(hero)home.append(hero);content.append(home);
const emergency=screen('emergencias','Te necesito');const es=$('#emergencySection');if(es){es.classList.remove('hidden');emergency.append(es)}content.append(emergency);
const capsules=screen('capsulas','Para el futuro');const cs=$('#capsulesSection');if(cs)capsules.append(cs);content.append(capsules);
const map=screen('mapa','Lugares por vivir');const ts=$('#travelSection');if(ts)map.append(ts);const fs=$('#foodSection');if(fs)fs.remove();content.append(map);
const history=screen('historia','Nuestra historia');const ow=$('#openWhenSection');const tl=$('#timelineSection');const love=$('#calculateLove')?.closest('.section');[ow,love,tl].forEach(x=>x&&history.append(x));content.append(history);
const settings=screen('ajustes','Nuestra cajita por dentro');settings.innerHTML+=`<div class="settings-card card"><h3>Tu lado de la cajita</h3><label class="field-label">Cómo llamas al otro</label><input id="profileNickname" class="field-control"><label class="field-label">Frase de bienvenida</label><textarea id="profileWelcome" class="field-control" rows="3"></textarea><label class="field-label">Tu emoji</label><input id="profileEmoji" class="field-control" maxlength="8"><div class="settings-actions"><button id="saveProfile" class="primary-btn compact">Guardar mi perfil</button><button id="settingsSignOut" class="secondary-btn compact">Cerrar sesión</button></div><p id="profileStatus" class="cajita-status"></p></div>`;content.append(settings);
const mobile=make('nav','mobile-cajita-nav');[['inicio','🏠','Inicio'],['capsulas','💌','Cápsulas'],['album','📷','Álbum'],['mapa','🗺️','Mapa']].forEach(r=>mobile.append(navButton(...r)));const more=make('button','',`<span>•••</span>Más`);more.onclick=()=>$('.mobile-more-sheet').classList.toggle('hidden');mobile.append(more);document.body.append(mobile);const sheet=make('div','mobile-more-sheet hidden');[['emergencias','🫂 Te necesito'],['historia','📖 Nuestra historia'],['ajustes','⚙️ Ajustes']].forEach(([id,l])=>{const b=make('button','',l);b.onclick=()=>navigate(id);sheet.append(b)});document.body.append(sheet);
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>b.dataset.home==='album'?location.href='/galeria.html':navigate(b.dataset.home));$('#saveProfile').onclick=saveProfile;$('#settingsSignOut').onclick=()=>db.auth.signOut();navigate((location.hash||'#inicio').slice(1));window.addEventListener('hashchange',()=>navigate((location.hash||'#inicio').slice(1)));
}

async function loadIdentity(){const s=(await db.auth.getSession()).data.session;session=s;if(!s)return;const {data:members}=await db.from('couple_members').select('id,display_name');me=members?.find(x=>x.id===s.user.id);partner=members?.find(x=>x.id!==s.user.id);if(!me)return;const {data:p}=await db.from('couple_profiles').select('*').eq('user_id',me.id).maybeSingle();profile=p||null;applyIdentity();await loadEmergencies()}
function applyIdentity(){const nick=profile?.partner_nickname||partner?.display_name||'amor';$('#personalGreeting').textContent=`Hola, ${me.display_name} ${profile?.personal_emoji||'❤️'}`;$('#personalWelcome').textContent=profile?.welcome_phrase||`Aquí guardamos todo lo que ${nick} y tú todavía tenéis por vivir.`;$('#partnerName').textContent=me.display_name;$('#heroSubtitle').textContent=partner?`${partner.display_name} está al otro lado de esta cajita.`:'La otra mitad de la cajita todavía no ha entrado.';$('#profileNickname').value=profile?.partner_nickname||partner?.display_name||'';$('#profileWelcome').value=profile?.welcome_phrase||'';$('#profileEmoji').value=profile?.personal_emoji||'❤️';const loveHeading=$('#calculateLove')?.closest('.section')?.querySelector('h2');if(loveHeading)loveHeading.textContent=`¿Cuánto te quiere ${partner?.display_name||'tu persona'}?`}
async function saveProfile(){const row={user_id:me.id,partner_nickname:$('#profileNickname').value.trim(),welcome_phrase:$('#profileWelcome').value.trim(),personal_emoji:$('#profileEmoji').value.trim()||'❤️',updated_at:new Date().toISOString()};const {error}=await db.from('couple_profiles').upsert(row,{onConflict:'user_id'});$('#profileStatus').textContent=error?error.message:'Guardado ❤️';if(!error){profile={...(profile||{}),...row};applyIdentity()}}

async function loadEmergencies(){const section=$('#emergencySection');if(!section)return;section.innerHTML=`<div class="section-heading"><span>MENSAJES DEL OTRO LADO</span><h2>¿Qué necesitas ahora mismo?</h2><p id="emergencyIntro"></p></div><div class="emergency-toolbar"><button id="newEmergency" class="primary-btn compact">Preparar un mensaje para ${esc(partner?.display_name||'el otro')}</button><button id="seedEmergency" class="secondary-btn compact">Crear mensajes iniciales</button></div><div id="receivedActions" class="actions-grid"></div><div class="emergency-manage"><h3>Lo que tú has preparado para ${esc(partner?.display_name||'el otro')}</h3><div id="authoredActions" class="emergency-list"></div></div>`;$('#newEmergency').onclick=()=>openEmergencyEditor();$('#seedEmergency').onclick=seedDefaults;if(!partner){$('#emergencyIntro').textContent='La otra cuenta debe crearse antes de poder enviaros mensajes.';$('#newEmergency').disabled=true;$('#seedEmergency').disabled=true;$('#receivedActions').innerHTML='<div class="partner-note">Cuando la otra persona entre, aquí aparecerán los mensajes que haya preparado para ti.</div>';return}
const {data}=await db.from('emergency_actions').select('*').order('sort_order').order('created_at');received=(data||[]).filter(x=>x.target_user_id===me.id&&x.is_active&&(!x.starts_at||new Date(x.starts_at)<=new Date()));authored=(data||[]).filter(x=>x.author_id===me.id);renderEmergencies()}
function renderEmergencies(){const rg=$('#receivedActions');rg.innerHTML='';received.forEach(a=>{const b=make('button','action-card',`<span class="icon">${esc(a.emoji)}</span><strong>${esc(a.button_text)}</strong><small>${esc(a.title)}</small>`);b.onclick=()=>activateEmergency(a);rg.append(b)});if(!received.length)rg.innerHTML=`<div class="emergency-empty">${partner?.display_name||'La otra persona'} todavía no ha preparado mensajes para ti.</div>`;const ag=$('#authoredActions');ag.innerHTML='';authored.forEach(a=>{const row=make('div','emergency-row',`<div><strong>${esc(a.emoji)} ${esc(a.button_text)}</strong><small style="display:block">${a.is_active?'Activo':'Archivado'} · ${a.send_notification?'Con aviso':'Sin aviso'}</small></div><div class="emergency-row-actions"></div>`);const edit=make('button','mini-btn','Editar');edit.onclick=()=>openEmergencyEditor(a);const toggle=make('button','mini-btn',a.is_active?'Ocultar':'Activar');toggle.onclick=()=>toggleAction(a);row.querySelector('.emergency-row-actions').append(edit,toggle);ag.append(row)});if(!authored.length)ag.innerHTML='<div class="emergency-empty">Todavía no has preparado ningún mensaje para el otro.</div>'}
async function activateEmergency(a){showMessage(a.emoji,a.title,a.internal_message);if(!a.send_notification||!partner)return;try{await fetch(`${URL}/functions/v1/send-push`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY,authorization:`Bearer ${session.access_token}`},body:JSON.stringify({targetUserId:partner.id,title:`${a.emoji} ${me.display_name} te necesita`,message:a.notification_text||`${me.display_name} ha activado: ${a.button_text}`,url:'/#emergencias',tag:`emergency-${a.category}`})})}catch(e){console.error(e)}try{await db.from('assistance_requests').insert({requested_by:me.id})}catch{}}
function showMessage(icon,title,text){$('#modalIcon').textContent=icon;$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function openEmergencyEditor(a={}){if(!partner)return;let modal=$('#emergencyEditor');if(!modal){modal=make('div','cajita-modal hidden');modal.id='emergencyEditor';modal.innerHTML=`<div class="cajita-modal-card"><button id="closeEmergencyEditor" class="modal-close">×</button><div class="modal-icon">🫂</div><h3>Mensaje para el otro lado</h3><div class="cajita-form-grid"><div><label class="field-label">Emoji</label><input id="eeEmoji" class="field-control"></div><div><label class="field-label">Categoría</label><input id="eeCategory" class="field-control"></div><div class="full"><label class="field-label">Texto del botón</label><input id="eeButton" class="field-control"></div><div class="full"><label class="field-label">Título</label><input id="eeTitle" class="field-control"></div><div class="full"><label class="field-label">Mensaje que verá al pulsar</label><textarea id="eeInternal" class="field-control" rows="4"></textarea></div><div class="full"><label class="field-label">Notificación que recibirás tú</label><textarea id="eeNotification" class="field-control" rows="3"></textarea></div><label class="check-row full"><input id="eeSend" type="checkbox"><span>Enviar notificación</span></label><label class="check-row full"><input id="eeSurprise" type="checkbox"><span>Ocultar como sorpresa hasta que se use</span></label></div><button id="saveEmergency" class="primary-btn compact">Guardar mensaje</button><p id="eeStatus" class="cajita-status"></p></div>`;document.body.append(modal);$('#closeEmergencyEditor').onclick=()=>modal.classList.add('hidden')}
modal.dataset.id=a.id||'';$('#eeEmoji').value=a.emoji||'❤️';$('#eeCategory').value=a.category||'custom';$('#eeButton').value=a.button_text||'';$('#eeTitle').value=a.title||'';$('#eeInternal').value=a.internal_message||'';$('#eeNotification').value=a.notification_text||'';$('#eeSend').checked=a.send_notification!==false;$('#eeSurprise').checked=!!a.is_surprise;$('#eeStatus').textContent='';$('#saveEmergency').onclick=saveEmergency;modal.classList.remove('hidden')}
async function saveEmergency(){const id=$('#emergencyEditor').dataset.id;const row={author_id:me.id,target_user_id:partner.id,emoji:$('#eeEmoji').value.trim()||'❤️',category:$('#eeCategory').value.trim()||'custom',button_text:$('#eeButton').value.trim(),title:$('#eeTitle').value.trim(),internal_message:$('#eeInternal').value.trim(),notification_text:$('#eeNotification').value.trim(),send_notification:$('#eeSend').checked,is_surprise:$('#eeSurprise').checked,updated_at:new Date().toISOString()};if(!row.button_text||!row.title||!row.internal_message)return $('#eeStatus').textContent='Completa botón, título y mensaje.';const q=id?db.from('emergency_actions').update(row).eq('id',id):db.from('emergency_actions').insert(row);const {error}=await q;if(error)return $('#eeStatus').textContent=error.message;$('#emergencyEditor').classList.add('hidden');await loadEmergencies()}
async function toggleAction(a){await db.from('emergency_actions').update({is_active:!a.is_active,updated_at:new Date().toISOString()}).eq('id',a.id);await loadEmergencies()}
async function seedDefaults(){if(!partner||authored.length)return;const base=[['😔','Estoy teniendo un día malo','Día malo','Para un momento. No tienes que solucionarlo todo hoy. Estoy contigo.','😔 Necesito un poco de apoyo hoy','bad_day'],['🥺','Necesito cariño','Necesito cariño','Has avisado. Ahora respira: hay abrazos reservados para ti.','🥺 Necesito una dosis de cariño','affection'],['📞','Necesito hablar','Necesito hablar','Tu mensaje ha llegado. No estás solo/a con esto.','📞 Necesito hablar contigo cuando puedas','talk'],['🫂','Estoy agobiado/a','Estoy agobiado/a','Una cosa cada vez. Yo estoy contigo, incluso desde lejos.','🫂 Estoy agobiado/a; un mensaje tuyo ayudaría','overwhelmed'],['😂','Hazme reír','Necesito reírme','Se ha activado el protocolo de humor de calidad discutible.','😂 Necesito refuerzos de humor','laugh']].map((x,i)=>({author_id:me.id,target_user_id:partner.id,emoji:x[0],button_text:x[1],title:x[2],internal_message:x[3],notification_text:x[4],category:x[5],sort_order:i,send_notification:true}));const {error}=await db.from('emergency_actions').insert(base);if(error)alert(error.message);await loadEmergencies()}

buildShell();db.auth.onAuthStateChange((_e,s)=>{session=s;setTimeout(loadIdentity,0)});await loadIdentity();