import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const db=createClient('https://bcyvxxegkguygdbvxoth.supabase.co','sb_publishable_wILGSQL-gq4YMoZSeJ8rAQ_oviCl8BB');
const PAGE=20;let rows=[],shown=PAGE,filter='all',sort='newest',search='';
const q=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function boot(){const{data:{session}}=await db.auth.getSession();if(!session){q('#galleryAuth').innerHTML='<p>Necesitas iniciar sesión desde la página principal.</p><a class="primary-btn" href="/">Ir a iniciar sesión</a>';return;}q('#galleryAuth').classList.add('hidden');q('#galleryPrivate').classList.remove('hidden');await load();}
async function load(){q('#galleryPageStatus').textContent='Cargando recuerdos…';const{data,error}=await db.from('gallery_media').select('*').order('memory_date',{ascending:false});if(error){q('#galleryPageStatus').textContent=error.message;return;}rows=await Promise.all((data||[]).map(async r=>{const{data:signed}=await db.storage.from('couple-gallery').createSignedUrl(r.storage_path,3600);return{...r,url:signed?.signedUrl};}));q('#galleryPageStatus').textContent='';render();}
function current(){let list=rows.filter(r=>filter==='all'||(filter==='favorite'?r.favorite:r.media_type===filter));if(search){const s=search.toLowerCase();list=list.filter(r=>(r.title||'').toLowerCase().includes(s)||(r.description||'').toLowerCase().includes(s));}list.sort((a,b)=>sort==='oldest'?String(a.memory_date).localeCompare(String(b.memory_date)):String(b.memory_date).localeCompare(String(a.memory_date)));return list;}
function render(){const list=current(),slice=list.slice(0,shown);q('#galleryPageGrid').innerHTML=slice.map(r=>`<article class="gallery-page-card"><button class="gallery-media-button" data-open="${r.id}">${r.media_type==='video'?`<video src="${r.url}" muted playsinline></video>`:`<img src="${r.url}" loading="lazy" alt="${esc(r.title)}">`}</button><div class="gallery-page-copy"><span>${new Date(r.memory_date+'T12:00:00').toLocaleDateString('es-ES')}</span><h3>${esc(r.title)}</h3><p>${esc(r.description||'')}</p></div></article>`).join('')||'<p>No hay recuerdos con este filtro.</p>';q('#galleryLoadMore').hidden=shown>=list.length;q('#galleryPageStatus').textContent=`Mostrando ${Math.min(shown,list.length)} de ${list.length} recuerdos.`;}
q('.gallery-page-controls').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;q('[data-filter].active')?.classList.remove('active');b.classList.add('active');filter=b.dataset.filter;shown=PAGE;render();});
q('#galleryPageSort').addEventListener('change',e=>{sort=e.target.value;render();});q('#galleryPageSearch').addEventListener('input',e=>{search=e.target.value.trim();shown=PAGE;render();});q('#galleryLoadMore').addEventListener('click',()=>{shown+=PAGE;render();});
q('#galleryPageGrid').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(!b)return;const r=rows.find(x=>x.id===b.dataset.open);if(!r)return;const w=window.open('','_blank');w.document.write(r.media_type==='video'?`<video src="${r.url}" controls autoplay style="max-width:100%;max-height:100vh"></video>`:`<img src="${r.url}" style="max-width:100%;max-height:100vh">`);});
boot();