(function () {
  'use strict';

  const SUPABASE_URL = 'https://bcyvxxegkguygdbvxoth.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_wILGSQL-gq4YMoZSeJ8rAQ_oviCl8BB';
  const RELATIONSHIP_START = '2021-08-17';
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => Array.from(document.querySelectorAll(s));
  const esc = (v) => String(v == null ? '' : v).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state = { db:null, session:null, me:null, partner:null, members:[], profile:null, route:'home', gallery:[], places:[], emergencies:[] };

  function setStatus(message, error) {
    const el = $('#authStatus');
    if (!el) return;
    el.textContent = message || '';
    el.style.color = error ? '#a13f54' : '';
  }
  function toast(message) {
    const root = $('#toastRoot');
    if (!root) return;
    const el = document.createElement('div');
    el.className = 'toast'; el.textContent = message;
    root.appendChild(el); setTimeout(() => el.remove(), 3000);
  }
  function friendly(error) {
    const m = error && error.message ? error.message : String(error || '');
    if (/failed to fetch|networkerror|load failed/i.test(m)) return 'No se pudo conectar con la cajita. Comprueba la conexión y vuelve a intentarlo.';
    if (/invalid login credentials/i.test(m)) return 'El correo o la contraseña no son correctos.';
    if (/rate limit|after \d+ seconds/i.test(m)) return 'Se han hecho demasiados intentos seguidos. Espera un minuto y vuelve a probar.';
    return m || 'Ha ocurrido un error.';
  }
  function modal(html) {
    const root = $('#modalRoot');
    root.innerHTML = '<div class="modal-wrap"><button class="modal-backdrop" data-close-modal aria-label="Cerrar"></button><div class="modal-card"><button class="modal-close" data-close-modal>×</button>' + html + '</div></div>';
    $$('[data-close-modal]').forEach((b) => b.addEventListener('click', () => { root.innerHTML=''; }));
  }
  function fmtDate(v) { return v ? new Date(v).toLocaleDateString('es-ES',{day:'2-digit',month:'short',year:'numeric'}) : ''; }
  function daysTogether() { return Math.max(0, Math.floor((Date.now() - new Date(RELATIONSHIP_START+'T00:00:00').getTime()) / 86400000)); }
  function partnerName() { return (state.profile && state.profile.partner_nickname) || (state.partner && state.partner.display_name) || 'amor'; }
  function memberName(id) { const m = state.members.find((x)=>x.id===id); return m ? m.display_name : 'Nosotros'; }

  function wireImmediateUI() {
    document.addEventListener('click', (e) => {
      const toggle = e.target.closest('[data-toggle-password]');
      if (toggle) {
        const input = document.getElementById(toggle.dataset.togglePassword);
        if (input) { const show = input.type === 'password'; input.type = show ? 'text' : 'password'; toggle.textContent = show ? 'Ocultar' : 'Mostrar'; }
        return;
      }
      const route = e.target.closest('[data-route]');
      if (route && !$('#privateApp').classList.contains('hidden')) { e.preventDefault(); navigate(route.dataset.route); }
    });
    $('#signInBtn').addEventListener('click', signIn);
    $('#signUpBtn').addEventListener('click', signUp);
    $('#forgotBtn').addEventListener('click', () => openRecovery(false));
    $('#magicBtn').addEventListener('click', magicLink);
    $('#authPassword').addEventListener('keydown', (e) => { if (e.key === 'Enter') signIn(); });
    $('#moreBtn').addEventListener('click', () => $('#moreSheet').classList.remove('hidden'));
    $$('[data-close-sheet]').forEach((b) => b.addEventListener('click', () => $('#moreSheet').classList.add('hidden')));
    $('#floatingNeedBtn').addEventListener('click', openNeedNow);
    $('#desktopNeedBtn').addEventListener('click', openNeedNow);
    window.addEventListener('hashchange', () => { if (state.session) navigate(routeFromHash(), false); });
  }

  function requireDb() {
    if (!state.db) { setStatus('El servicio de acceso todavía no ha cargado. Recarga la página en unos segundos.', true); return false; }
    return true;
  }
  async function signIn() {
    if (!requireDb()) return;
    const email=$('#authEmail').value.trim().toLowerCase(), password=$('#authPassword').value;
    if (!email || !password) return setStatus('Escribe tu correo y contraseña.', true);
    setStatus('Abriendo vuestra cajita…');
    try { const r=await state.db.auth.signInWithPassword({email,password}); if (r.error) throw r.error; }
    catch(e){ setStatus(friendly(e),true); }
  }
  async function signUp() {
    if (!requireDb()) return;
    const email=$('#authEmail').value.trim().toLowerCase(), password=$('#authPassword').value;
    if (!email || password.length<8) return setStatus('Usa un correo autorizado y una contraseña de al menos 8 caracteres.',true);
    setStatus('Creando tu lado de la cajita…');
    try { const r=await state.db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/'}}); if(r.error) throw r.error; setStatus('Cuenta creada. Revisa el correo para confirmarla.'); }
    catch(e){setStatus(friendly(e),true);}
  }
  async function magicLink() {
    if (!requireDb()) return;
    const email=$('#authEmail').value.trim().toLowerCase(); if(!email) return setStatus('Escribe primero tu correo.',true);
    setStatus('Enviando enlace mágico…');
    try { const r=await state.db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/'}}); if(r.error) throw r.error; setStatus('Enlace enviado. Abre el correo más reciente.'); }
    catch(e){setStatus(friendly(e),true);}
  }
  function openRecovery(newPassword) {
    if (newPassword) {
      modal('<span class="eyebrow">ACCESO PRIVADO</span><h2>Nueva contraseña</h2><p>Escribe una contraseña nueva. No necesitas conocer la anterior.</p><label class="field-label">Nueva contraseña</label><div class="password-row"><input id="reset1" class="field-control" type="password" minlength="8"><button class="password-toggle" data-toggle-password="reset1">Mostrar</button></div><label class="field-label">Repite la contraseña</label><div class="password-row"><input id="reset2" class="field-control" type="password" minlength="8"><button class="password-toggle" data-toggle-password="reset2">Mostrar</button></div><button id="saveReset" class="primary-btn full">Guardar contraseña</button><p id="resetStatus" class="status"></p>');
      $('#saveReset').addEventListener('click', saveNewPassword);
    } else {
      modal('<span class="eyebrow">ACCESO PRIVADO</span><h2>Crear o recuperar contraseña</h2><p>Te enviaremos un enlace seguro para crear una contraseña nueva.</p><label class="field-label">Correo</label><input id="resetEmail" class="field-control" type="email" value="'+esc($('#authEmail').value)+'"><button id="sendReset" class="primary-btn full">Enviar enlace</button><p id="resetStatus" class="status"></p>');
      $('#sendReset').addEventListener('click', sendRecovery);
    }
  }
  async function sendRecovery(){if(!requireDb())return;const email=$('#resetEmail').value.trim().toLowerCase(),s=$('#resetStatus');if(!email){s.textContent='Escribe tu correo.';return;}try{const r=await state.db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/?recovery=1'});if(r.error)throw r.error;s.textContent='Correo enviado. Usa el enlace más reciente.';}catch(e){s.textContent=friendly(e);}}
  async function saveNewPassword(){const a=$('#reset1').value,b=$('#reset2').value,s=$('#resetStatus');if(a.length<8){s.textContent='Mínimo 8 caracteres.';return;}if(a!==b){s.textContent='Las contraseñas no coinciden.';return;}try{const r=await state.db.auth.updateUser({password:a});if(r.error)throw r.error;s.textContent='Contraseña guardada ❤️';history.replaceState(null,'','/#home');setTimeout(()=>$('#modalRoot').innerHTML='',800);}catch(e){s.textContent=friendly(e);}}

  async function handleSession(session) {
    state.session=session;
    if (!session || !session.user) { state.me=state.partner=null; $('#authGate').classList.remove('hidden'); $('#privateApp').classList.add('hidden'); return; }
    try {
      const r=await state.db.from('couple_members').select('id,display_name,created_at').order('created_at'); if(r.error)throw r.error;
      state.members=r.data||[]; state.me=state.members.find((m)=>m.id===session.user.id);
      if(!state.me){await state.db.auth.signOut();return setStatus('Este correo no está autorizado.',true);}
      state.partner=state.members.find((m)=>m.id!==state.me.id)||null;
      const p=await state.db.from('couple_profiles').select('*').eq('user_id',state.me.id).maybeSingle(); state.profile=p.data||null;
      $('#authGate').classList.add('hidden'); $('#privateApp').classList.remove('hidden'); $('#sidebarName').textContent=state.me.display_name; $('#sidebarEmoji').textContent=(state.profile&&state.profile.personal_emoji)||'❤️'; $('#mobileProfileBtn').textContent=(state.profile&&state.profile.personal_emoji)||'❤️';
      navigate(routeFromHash(),false); loadBackground();
    } catch(e){setStatus(friendly(e),true);}
  }
  function routeFromHash(){const r=(location.hash||'#home').slice(1);return ['home','capsules','gallery','map','emergencies','history','settings'].includes(r)?r:'home';}
  function navigate(route,push){state.route=route;$('#moreSheet').classList.add('hidden');$$('[data-route]').forEach((b)=>b.classList.toggle('active',b.dataset.route===route));if(push!==false&&location.hash!=='#'+route)history.pushState(null,'','#'+route);renderRoute(route);window.scrollTo(0,0);}
  function page(title,eyebrow,body,actions){return '<div class="page"><div class="page-header"><div><span class="eyebrow">'+eyebrow+'</span><h1>'+title+'</h1></div>'+(actions?'<div class="page-actions">'+actions+'</div>':'')+'</div>'+body+'</div>';}

  async function renderRoute(route){const v=$('#view');v.innerHTML='<div class="page"><div class="skeleton"></div></div>';try{if(route==='home')await home();else if(route==='capsules')await capsules();else if(route==='gallery')await gallery();else if(route==='map')await mapView();else if(route==='emergencies')await emergencyManager();else if(route==='history')await historyView();else if(route==='settings')await settings();}catch(e){v.innerHTML=page('Algo no ha ido bien','NUESTRA CAJITA','<div class="empty">'+esc(friendly(e))+'</div>');}}
  async function home(){const [g,c,p]=await Promise.all([state.db.from('gallery_media').select('*').order('memory_date',{ascending:false}).limit(1),state.db.from('capsules').select('*').eq('recipient_id',state.me.id).gt('open_at',new Date().toISOString()).order('open_at').limit(1),state.db.from('shared_places').select('*').neq('status','visited').order('created_at',{ascending:false}).limit(1)]);const media=g.data&&g.data[0],cap=c.data&&c.data[0],place=p.data&&p.data[0];let img='';if(media){const s=await state.db.storage.from('couple-gallery').createSignedUrl(media.storage_path,10800);if(s.data&&s.data.signedUrl)img=s.data.signedUrl;}$('#view').innerHTML=page('Hola, '+esc(state.me.display_name)+' '+esc((state.profile&&state.profile.personal_emoji)||'❤️'),'UN RINCÓN SOLO NUESTRO','<section class="home-hero card"><p>'+esc((state.profile&&state.profile.welcome_phrase)||('Aquí guardamos todo lo que '+partnerName()+' y tú todavía tenéis por vivir.'))+'</p><div class="home-meta"><span class="pill">❤️ '+daysTogether().toLocaleString('es-ES')+' días siendo nosotros</span><span class="pill">🔒 Solo vosotros dos</span></div></section><div class="home-grid">'+(img?'<article class="memory-of-day card" data-route="gallery"><img src="'+img+'" alt="'+esc(media.title)+'"><div class="memory-copy"><small>📷 Recuerdo reciente</small><h3>'+esc(media.title)+'</h3></div></article>':'<div class="memory-of-day card"><div class="empty">📷 Guardad vuestro primer recuerdo.</div></div>')+'<div class="home-stack"><article class="mini-card card" data-route="capsules"><div class="icon">💌</div><span class="meta">PARA TI</span><h3>'+(cap?esc(cap.title):'Sin cápsulas esperando')+'</h3><p>'+(cap?'Se abre el '+fmtDate(cap.open_at)+'.':'Podéis dejaros mensajes para el futuro.')+'</p></article><article class="mini-card card" data-route="map"><div class="icon">🗺️</div><span class="meta">PRÓXIMO PLAN</span><h3>'+(place?esc(place.name):'¿Dónde nos vamos?')+'</h3><p>'+(place?esc(place.notes||place.address||'Pendiente'):'Guardad viajes y sitios por vivir.')+'</p></article><article class="mini-card card" id="homeNeed"><div class="icon">🫂</div><span class="meta">SI HOY HACE FALTA</span><h3>Te necesito</h3><p>Un toque y el otro sabrá que lo necesitas.</p></article></div></div>');$('#homeNeed').addEventListener('click',openNeedNow);}

  async function capsules(){const r=await state.db.from('capsules').select('id,author_id,recipient_id,title,open_at,secret_date,opened_at,created_at,capsule_contents(message)').order('created_at',{ascending:false});if(r.error)throw r.error;const list=r.data||[];const received=list.filter((x)=>x.recipient_id===state.me.id);const sent=list.filter((x)=>x.author_id===state.me.id);$('#view').innerHTML=page('Cápsulas','PARA NUESTRO YO FUTURO','<div class="tabs"><button class="tab active" data-list="received">Para mí</button><button class="tab" data-list="sent">Enviadas</button></div><div id="capsList"></div>',state.partner?'<button id="newCapsule" class="primary-btn">＋ Nueva cápsula</button>':'');function draw(arr,type){$('#capsList').innerHTML='<div class="capsule-grid">'+(arr.length?arr.map((c)=>{const open=new Date(c.open_at)<=new Date();return '<article class="capsule-card card"><span class="capsule-icon">'+(open?'💌':'🔒')+'</span><span class="meta">'+(type==='received'?'DE '+esc(memberName(c.author_id).toUpperCase()):'PARA '+esc(memberName(c.recipient_id).toUpperCase()))+'</span><h3>'+esc(c.title)+'</h3><p>'+(open?'Ya puede abrirse.':(c.secret_date&&type==='received'?'La fecha es sorpresa.':'Se abre el '+fmtDate(c.open_at)))+'</p>'+(open||type==='sent'?'<button class="primary-btn" data-cap="'+c.id+'">Abrir</button>':'')+'</article>';}).join(''):'<div class="empty">Todavía no hay cápsulas aquí.</div>')+'</div>';$$('[data-cap]').forEach((b)=>b.addEventListener('click',()=>{const c=list.find((x)=>x.id===b.dataset.cap);const cc=Array.isArray(c.capsule_contents)?c.capsule_contents[0]:c.capsule_contents;modal('<span class="eyebrow">💌 '+esc(c.title)+'</span><h2>'+esc(c.title)+'</h2><p style="white-space:pre-line">'+esc(cc&&cc.message||'')+'</p>');}));}draw(received,'received');$$('[data-list]').forEach((b)=>b.addEventListener('click',()=>{ $$('.tab').forEach((x)=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.list==='received'?received:sent,b.dataset.list);}));$('#newCapsule')&&$('#newCapsule').addEventListener('click',newCapsule);}
  function newCapsule(){modal('<span class="eyebrow">PARA '+esc(state.partner.display_name.toUpperCase())+'</span><h2>Nueva cápsula</h2><label class="field-label">Título</label><input id="capTitle" class="field-control"><label class="field-label">Mensaje</label><textarea id="capMessage" class="field-control" rows="6"></textarea><label class="field-label">Fecha</label><input id="capDate" class="field-control" type="date"><label class="check-row"><input id="capSecret" type="checkbox"><span>Fecha sorpresa</span></label><button id="saveCap" class="primary-btn full">Cerrar cápsula 🔒</button><p id="capStatus" class="status"></p>');$('#saveCap').addEventListener('click',async()=>{const t=$('#capTitle').value.trim(),m=$('#capMessage').value.trim(),d=$('#capDate').value,s=$('#capStatus');if(!t||!m||!d){s.textContent='Completa título, mensaje y fecha.';return;}const c=await state.db.from('capsules').insert({author_id:state.me.id,recipient_id:state.partner.id,title:t,open_at:new Date(d+'T12:00:00').toISOString(),secret_date:$('#capSecret').checked}).select('id').single();if(c.error){s.textContent=friendly(c.error);return;}const cc=await state.db.from('capsule_contents').insert({capsule_id:c.data.id,message:m});if(cc.error){s.textContent=friendly(cc.error);return;}$('#modalRoot').innerHTML='';toast('Cápsula guardada 🔒');capsules();});}

  async function gallery(){const r=await state.db.from('gallery_media').select('*').order('memory_date',{ascending:false}).limit(60);if(r.error)throw r.error;state.gallery=r.data||[];const withUrls=await Promise.all(state.gallery.map(async(m)=>{const s=await state.db.storage.from('couple-gallery').createSignedUrl(m.storage_path,10800);return Object.assign({},m,{url:s.data&&s.data.signedUrl});}));$('#view').innerHTML=page('Nuestro álbum','NUESTROS RECUERDOS','<div class="gallery-filters"><button class="chip active" data-g="all">Todo</button><button class="chip" data-g="image">Fotos</button><button class="chip" data-g="video">Vídeos</button><button class="chip" data-g="favorite">Favoritos</button></div><div id="gGrid" class="gallery-grid"></div>','<button id="uploadMemory" class="primary-btn">＋ Guardar recuerdo</button>');function draw(f){const arr=withUrls.filter((m)=>f==='all'||m.media_type===f||(f==='favorite'&&m.favorite));$('#gGrid').innerHTML=arr.length?arr.map((m)=>'<article class="gallery-card card"><div class="gallery-media">'+(m.media_type==='video'?'<video src="'+m.url+'" controls preload="metadata"></video>':'<img src="'+m.url+'" loading="lazy" alt="'+esc(m.title)+'">')+'</div><div class="copy"><span class="meta">'+(m.favorite?'⭐ ':'')+fmtDate(m.memory_date)+'</span><h3>'+esc(m.title)+'</h3><p>'+esc(m.description||'')+'</p></div></article>').join(''):'<div class="empty">No hay recuerdos en este filtro.</div>';}draw('all');$$('[data-g]').forEach((b)=>b.addEventListener('click',()=>{ $$('.chip').forEach((x)=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.g);}));$('#uploadMemory').addEventListener('click',uploadMemory);}
  function uploadMemory(){modal('<span class="eyebrow">NUESTRO ÁLBUM</span><h2>Guardar recuerdo</h2><label class="field-label">Foto o vídeo</label><input id="memFile" class="field-control" type="file" accept="image/*,video/*"><label class="field-label">Título</label><input id="memTitle" class="field-control"><label class="field-label">Historia</label><textarea id="memDesc" class="field-control" rows="4"></textarea><label class="field-label">Fecha</label><input id="memDate" class="field-control" type="date" value="'+new Date().toISOString().slice(0,10)+'"><label class="check-row"><input id="memFav" type="checkbox"><span>Especial ⭐</span></label><button id="saveMem" class="primary-btn full">Guardar recuerdo ❤️</button><p id="memStatus" class="status"></p>');$('#saveMem').addEventListener('click',async()=>{const f=$('#memFile').files[0],t=$('#memTitle').value.trim(),d=$('#memDate').value,s=$('#memStatus');if(!f||!t||!d){s.textContent='Selecciona archivo, título y fecha.';return;}if(f.size>60*1024*1024){s.textContent='Máximo 60 MB.';return;}s.textContent='Guardando…';const ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=state.me.id+'/'+crypto.randomUUID()+'.'+ext,type=f.type.startsWith('video/')?'video':'image';const up=await state.db.storage.from('couple-gallery').upload(path,f,{upsert:false});if(up.error){s.textContent=friendly(up.error);return;}const ins=await state.db.from('gallery_media').insert({uploaded_by:state.me.id,media_type:type,storage_path:path,title:t,description:$('#memDesc').value.trim(),memory_date:d,favorite:$('#memFav').checked});if(ins.error){s.textContent=friendly(ins.error);return;}$('#modalRoot').innerHTML='';toast('Recuerdo guardado ❤️');gallery();});}

  async function mapView(){const r=await state.db.from('shared_places').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;state.places=r.data||[];$('#view').innerHTML=page('Lugares por vivir','NUESTRO MAPA','<div class="map-toolbar"><input id="placeSearch" class="field-control" placeholder="Buscar ciudad, restaurante o lugar…"><select id="placeCategory" class="field-control"><option value="travel">✈️ Viaje</option><option value="restaurant">🍽️ Restaurante</option><option value="cafe">☕ Café</option><option value="escape">🏖️ Escapada</option><option value="special">❤️ Especial</option></select><button id="findPlace" class="secondary-btn">Buscar</button></div><div id="placeResults"></div><div id="placesGrid" class="places-grid"></div>');drawPlaces();$('#findPlace').addEventListener('click',searchPlace);$('#placeSearch').addEventListener('keydown',(e)=>{if(e.key==='Enter')searchPlace();});}
  function drawPlaces(){const icons={travel:'✈️',restaurant:'🍽️',cafe:'☕',escape:'🏖️',special:'❤️'};$('#placesGrid').innerHTML=state.places.length?state.places.map((p)=>'<article class="place-card card"><span class="meta">'+(icons[p.category]||'📍')+' '+(p.status==='visited'?'VISITADO':'PENDIENTE')+'</span><h3>'+esc(p.name)+'</h3><p>'+esc(p.address||'')+'</p><small>'+esc(p.notes||'')+'</small><div class="place-actions"><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+p.latitude+','+p.longitude+'">Abrir mapa</a>'+(p.status!=='visited'?'<button data-visit="'+p.id+'">Marcar visitado</button>':'')+'</div></article>').join(''):'<div class="empty">No hay lugares todavía.</div>';$$('[data-visit]').forEach((b)=>b.addEventListener('click',async()=>{await state.db.from('shared_places').update({status:'visited',visited_at:new Date().toISOString().slice(0,10),updated_at:new Date().toISOString()}).eq('id',b.dataset.visit);mapView();}));}
  async function searchPlace(){const q=$('#placeSearch').value.trim();if(!q)return;$('#placeResults').innerHTML='<p class="status">Buscando…</p>';try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q),{headers:{'Accept-Language':'es'}});const arr=await res.json();$('#placeResults').innerHTML=arr.map((x,i)=>'<button class="mini-card card" data-result="'+i+'"><strong>'+esc(x.name||x.display_name.split(',')[0])+'</strong><p>'+esc(x.display_name)+'</p></button>').join('');$$('[data-result]').forEach((b)=>b.addEventListener('click',()=>savePlace(arr[Number(b.dataset.result)])));}catch(e){$('#placeResults').innerHTML='<p class="status">No se pudo buscar ahora mismo.</p>';}}
  function savePlace(x){modal('<span class="eyebrow">NUEVO LUGAR</span><h2>'+esc(x.name||x.display_name.split(',')[0])+'</h2><label class="field-label">Notas</label><textarea id="pNotes" class="field-control" rows="3"></textarea><button id="savePlace" class="primary-btn full">Guardar</button>');$('#savePlace').addEventListener('click',async()=>{const r=await state.db.from('shared_places').insert({created_by:state.me.id,name:x.name||x.display_name.split(',')[0],category:$('#placeCategory')?$('#placeCategory').value:'special',address:x.display_name,latitude:Number(x.lat),longitude:Number(x.lon),notes:$('#pNotes').value.trim()});if(r.error)return toast(friendly(r.error));$('#modalRoot').innerHTML='';toast('Lugar guardado 🗺️');mapView();});}

  async function loadEmergencies(){const r=await state.db.from('emergency_actions').select('*').order('sort_order').order('created_at');if(r.error)throw r.error;state.emergencies=r.data||[];}
  async function openNeedNow(){if(!state.session)return;if(!state.partner)return toast('La otra mitad todavía no está disponible.');await loadEmergencies();const arr=state.emergencies.filter((a)=>a.target_user_id===state.me.id&&a.is_active&&(!a.starts_at||new Date(a.starts_at)<=new Date()));modal('<span class="eyebrow">TE NECESITO</span><h2>¿Qué necesitas ahora mismo?</h2><div class="emergency-use-grid">'+(arr.length?arr.map((a)=>'<button class="emergency-action" data-use="'+a.id+'"><span class="icon">'+esc(a.emoji)+'</span><strong>'+esc(a.button_text)+'</strong><small>'+esc(a.title)+'</small></button>').join(''):'<div class="empty">Todavía no hay mensajes preparados para ti.</div>')+'</div>');$$('[data-use]').forEach((b)=>b.addEventListener('click',()=>activateEmergency(arr.find((a)=>a.id===b.dataset.use))));}
  async function activateEmergency(a){$('#modalRoot').innerHTML='';modal('<div style="font-size:2.4rem">'+esc(a.emoji)+'</div><h2>'+esc(a.title)+'</h2><p>'+esc(a.internal_message)+'</p>');if(a.send_notification&&state.partner){try{await fetch(SUPABASE_URL+'/functions/v1/send-push',{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_KEY,authorization:'Bearer '+state.session.access_token},body:JSON.stringify({targetUserId:state.partner.id,title:a.emoji+' '+state.me.display_name+' te necesita',message:a.notification_text||a.button_text,url:'/#emergencies',tag:'emergency-'+a.category})});}catch(e){}}await state.db.from('assistance_requests').insert({requested_by:state.me.id,requested_from:state.partner.id,assistance_type:a.category,message:a.button_text});}
  async function emergencyManager(){await loadEmergencies();const own=state.emergencies.filter((a)=>a.author_id===state.me.id);$('#view').innerHTML=page('Mensajes para el otro','TE NECESITO','<div class="emergency-manage-list">'+(own.length?own.map((a)=>'<article class="manage-row card"><div><strong>'+esc(a.emoji)+' '+esc(a.button_text)+'</strong><small>'+(a.is_active?'Activo':'Archivado')+'</small></div><div class="row-actions"><button data-edit="'+a.id+'">Editar</button><button data-toggle="'+a.id+'">'+(a.is_active?'Ocultar':'Activar')+'</button></div></article>').join(''):'<div class="empty">Todavía no has preparado mensajes.</div>')+'</div>',state.partner?'<button id="newEmergency" class="primary-btn">＋ Nuevo mensaje</button>':'');$('#newEmergency')&&$('#newEmergency').addEventListener('click',()=>editEmergency(null));$$('[data-edit]').forEach((b)=>b.addEventListener('click',()=>editEmergency(own.find((a)=>a.id===b.dataset.edit))));$$('[data-toggle]').forEach((b)=>b.addEventListener('click',async()=>{const a=own.find((x)=>x.id===b.dataset.toggle);await state.db.from('emergency_actions').update({is_active:!a.is_active,updated_at:new Date().toISOString()}).eq('id',a.id);emergencyManager();}));}
  function editEmergency(a){a=a||{};modal('<span class="eyebrow">PARA '+esc(state.partner.display_name.toUpperCase())+'</span><h2>'+(a.id?'Editar':'Nuevo')+' mensaje</h2><label class="field-label">Emoji</label><input id="eEmoji" class="field-control" value="'+esc(a.emoji||'❤️')+'"><label class="field-label">Texto del botón</label><input id="eButton" class="field-control" value="'+esc(a.button_text||'')+'"><label class="field-label">Título</label><input id="eTitle" class="field-control" value="'+esc(a.title||'')+'"><label class="field-label">Mensaje que verá</label><textarea id="eMessage" class="field-control" rows="4">'+esc(a.internal_message||'')+'</textarea><label class="field-label">Notificación</label><textarea id="eNotify" class="field-control" rows="3">'+esc(a.notification_text||'')+'</textarea><label class="check-row"><input id="eSend" type="checkbox" '+(a.send_notification!==false?'checked':'')+'><span>Enviar notificación</span></label><button id="saveEmergency" class="primary-btn full">Guardar</button><p id="eStatus" class="status"></p>');$('#saveEmergency').addEventListener('click',async()=>{const row={author_id:state.me.id,target_user_id:state.partner.id,emoji:$('#eEmoji').value.trim()||'❤️',category:a.category||'custom',button_text:$('#eButton').value.trim(),title:$('#eTitle').value.trim(),internal_message:$('#eMessage').value.trim(),notification_text:$('#eNotify').value.trim(),send_notification:$('#eSend').checked,updated_at:new Date().toISOString()};if(!row.button_text||!row.title||!row.internal_message){$('#eStatus').textContent='Completa botón, título y mensaje.';return;}const r=a.id?await state.db.from('emergency_actions').update(row).eq('id',a.id):await state.db.from('emergency_actions').insert(row);if(r.error){$('#eStatus').textContent=friendly(r.error);return;}$('#modalRoot').innerHTML='';toast('Mensaje guardado ❤️');emergencyManager();});}

  async function historyView(){const [p,g,c]=await Promise.all([state.db.from('shared_places').select('*').eq('status','visited').order('visited_at',{ascending:false}),state.db.from('gallery_media').select('*').eq('favorite',true).order('memory_date',{ascending:false}),state.db.from('capsules').select('*').not('opened_at','is',null).order('opened_at',{ascending:false})]);let items=[{date:RELATIONSHIP_START,title:'Empieza nuestro nosotros',icon:'❤️',text:'El comienzo de vuestra historia.'}];(p.data||[]).forEach((x)=>items.push({date:x.visited_at,title:x.name,icon:'📍',text:'Un lugar que ya forma parte de vosotros.'}));(g.data||[]).forEach((x)=>items.push({date:x.memory_date,title:x.title,icon:'📷',text:'Un recuerdo especial del álbum.'}));(c.data||[]).forEach((x)=>items.push({date:x.opened_at,title:x.title,icon:'💌',text:'Una cápsula que ya fue abierta.'}));items=items.filter((x)=>x.date).sort((a,b)=>new Date(b.date)-new Date(a.date));$('#view').innerHTML=page('Lo que ya es nuestro','NUESTRA HISTORIA','<div class="timeline">'+items.map((i)=>'<article class="timeline-item"><time>'+fmtDate(i.date)+'</time><h3>'+i.icon+' '+esc(i.title)+'</h3><p>'+esc(i.text)+'</p></article>').join('')+'</div>');}
  async function settings(){const notif=('Notification'in window)?Notification.permission:'no compatible';$('#view').innerHTML=page('Ajustes','POR DENTRO','<div class="settings-grid"><section class="settings-card card"><h3>Tu lado de la cajita</h3><label class="field-label">Cómo llamas al otro</label><input id="sNick" class="field-control" value="'+esc((state.profile&&state.profile.partner_nickname)||(state.partner&&state.partner.display_name)||'')+'"><label class="field-label">Frase de bienvenida</label><textarea id="sWelcome" class="field-control" rows="3">'+esc((state.profile&&state.profile.welcome_phrase)||'')+'</textarea><label class="field-label">Tu emoji</label><input id="sEmoji" class="field-control" value="'+esc((state.profile&&state.profile.personal_emoji)||'❤️')+'"><button id="saveProfile" class="primary-btn full">Guardar</button></section><section class="settings-card card"><h3>Cuenta</h3><p>'+esc(state.session.user.email||'')+'</p><button id="changePass" class="secondary-btn">🔑 Cambiar contraseña</button><button id="logout" class="secondary-btn">Cerrar sesión</button></section><section class="settings-card card"><h3>Notificaciones</h3><p>Permiso: <strong>'+esc(notif)+'</strong></p><p>Los avisos de “Te necesito” usan notificaciones push cuando están activadas.</p></section></div>');$('#saveProfile').addEventListener('click',saveProfile);$('#changePass').addEventListener('click',()=>openRecovery(true));$('#logout').addEventListener('click',()=>state.db.auth.signOut());}
  async function saveProfile(){const row={user_id:state.me.id,partner_nickname:$('#sNick').value.trim(),welcome_phrase:$('#sWelcome').value.trim(),personal_emoji:$('#sEmoji').value.trim()||'❤️',updated_at:new Date().toISOString()};const r=await state.db.from('couple_profiles').upsert(row,{onConflict:'user_id'});if(r.error)return toast(friendly(r.error));state.profile=Object.assign({},state.profile||{},row);$('#sidebarEmoji').textContent=row.personal_emoji;$('#mobileProfileBtn').textContent=row.personal_emoji;toast('Ajustes guardados ❤️');}
  async function loadBackground(){try{const r=await state.db.from('gallery_media').select('storage_path').eq('media_type','image').order('memory_date',{ascending:false}).limit(1).maybeSingle();if(!r.data)return;const s=await state.db.storage.from('couple-gallery').createSignedUrl(r.data.storage_path,10800);if(s.data&&s.data.signedUrl){const bg=$('#memoryBackground');bg.style.backgroundImage='url("'+s.data.signedUrl+'")';bg.classList.add('ready');}}catch(e){}}

  async function bootstrap() {
    wireImmediateUI();
    if (!window.supabase || !window.supabase.createClient) { setStatus('No se ha podido cargar el servicio de acceso. Recarga la página.',true); return; }
    state.db = window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
    state.db.auth.onAuthStateChange((event,session)=>{ if(event==='PASSWORD_RECOVERY') setTimeout(()=>openRecovery(true),30); setTimeout(()=>handleSession(session),0); });
    try { const r=await state.db.auth.getSession(); await handleSession(r.data.session); const recovery=new URLSearchParams(location.search).get('recovery')==='1'||location.hash.indexOf('type=recovery')>=0; if(recovery&&r.data.session)openRecovery(true); }
    catch(e){setStatus(friendly(e),true);}
  }

  bootstrap();
})();